
---
apiVersion: v1
kind: Service
metadata:
  name: whiskey-shop
  namespace: dev
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: whiskey-shop
